language: python
sudo: false

matrix:
  include:
    - python: 3.6
      env: TOXENV=linter

    - python: 3.6
      env: TOXENV=packaging

cache:
  - pip
  - directories:
    - ${HOME}/.cache

install:
  - python -m pip install tox

script:
  - tox

branches:
  only:
  - master
  - release
